### PR TITLE
[#476] Fix order of rejection reasons

### LINKED ISSUE #476: Tally sheet report PE-39

### PR DESCRIPTION
**Pull request by callkalpa**
Fixes #476

### CODE REVIEW

File: web/results-tabulation-ui/src/components/election/extended-election/ParliamentElection2020/tally-sheet-edit/tally-sheet-edit-pe-39.js [hunk 1]
```diff
@@ -30,6 +30,8 @@ export default function TallySheetEdit_PE_39({history, election, tallySheet, mes
         const _rejectionReasonWiseVoteCountRowsMap = {};
         election.invalidVoteCategories.filter(invalidVoteCategory => {
             return invalidVoteCategory.invalidVoteCategoryType === "ELECTION"
+        }).sort((a,b) => {
```
Comment (dinukadesilva) [inline web/results-tabulation-ui/src/components/election/extended-election/ParliamentElection2020/tally-sheet-edit/tally-sheet-edit-pe-39.js]: You also can get this sorted from the backend itself

**Review by dinukadesilva — APPROVED** [review]
